# Use root/example as user/password credentials
version: '3.1'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 127.0.0.1:28001:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
