# Use root/example as user/password credentials
version: '3.1'

services:
  bot:
    build: .
    restart: always
    depends_on:
      - mongo
    env_file:
      - bot.env
  mongo:
    image: mongo
    restart: always
    env_file:
      - mongo.env
    ports:
      - 127.0.0.1:28001:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8089:8081
    env_file:
      - mongo.env
